---
  - name: Ensure Homebrew is installed
    include_role:
      name: geerlingguy.homebrew

  - name: Ensure source control providers are installed
    include_role:
      name: ccdc-scm-providers

  - name: Ensure a recent Python is installed
    include_role:
      name: ccdc-system-python

  - name: Install virtualisation packages
    homebrew_cask:
      - vagrant
      - vagrant-vmware-utility
      - vmware-fusion
      - virtualbox
    become: yes

  - name: Install Vagrant VMware plugin
    command: vagrant plugin install vagrant-vmware-desktop

  - name: Install Packer
    homebrew:
      - packer

  - name: Install macinbox
    gem:
      name: macinbox
      state: latest
    become: yes

  # https://www.vagrantup.com/docs/vmware/installation.html
  - name: Copy Vagrant VMware plugin licence file
    copy:
      src: "{{ vagrant_vmware_plugin_licence_file }}"
      dest: "/tmp/vagrant-vmware-plugin.lic"
    when: "{{ vagrant_vmware_plugin_licence_file }}"

  - name: Install Vagrant VMware plugin licence
    command: vagrant plugin license vagrant-vmware-desktop /tmp/vagrant-vmware-plugin.lic
    when: "{{ vagrant_vmware_plugin_licence_file }}"

  - name: Remove copy of Vagrant VMware plugin licence file
    file:
      path: /tmp/vagrant-vmware-plugin.lic
      state: absent

  # https://kb.vmware.com/s/article/1009244
  # https://communities.vmware.com/message/2104737#2104737
  - name: Activate VMware licence
    command: /Applications/VMware\ Fusion.app/Contents/Library/licenses/vmware-licenseTool enter "{{ vmware_licence_key }}" "CCDC" "CCDC" "{{ vmware_version }}" "Vmware Fusion for Mac OS" ""
    become: yes
    when: "{{ vmware_licence_key }}"

  - name: Download macOS {{ macos_version }} installer
    shell: softwareupdate --fetch-full-installer --full-installer-version {{ macos_version }}

  - name: Install Ansible
    pip:
      name:
        - ansible

  - name: Download Stage 1 provisioning repositories
    include_tasks:
      file: download_roles.yml
