---
  - name: Check out base box provisioning repos
    git:
      repo: "{{ repo.url }}"
      dest: "{{ provisioning_repo_destination }}/baseboxes/{{ repo.destination }}"
      accept_hostkey: yes
    loop: "{{ basebox_repos }}"
    loop_control:
      loop_var: repo

  - name: Check out build box provisioning repos
    git:
      repo: "{{ repo.url }}"
      dest: "{{ provisioning_repo_destination }}/buildboxes/{{ repo.destination }}"
      accept_hostkey: yes
    loop: "{{ buildbox_repos }}"
    loop_control:
      loop_var: repo

  - name: Check out test box provisioning repos
    git:
      repo: "{{ repo.url }}"
      dest: "{{ provisioning_repo_destination }}/testboxes/{{ repo.destination }}"
      accept_hostkey: yes
    loop: "{{ testbox_repos }}"
    loop_control:
      loop_var: repo

  - name: Check out provisioning development repos
    git:
      repo: "{{ repo.url }}"
      dest: "{{ provisioning_dev_destination }}/{{ repo.destination }}"
      accept_hostkey: yes
    loop: "{{ dev_repos }}"
    loop_control:
      loop_var: repo
