---
  - name: Ensure source control providers are installed
    include_role:
      name: ccdc-scm-providers

  - name: Install required tools
    win_chocolatey:
      name:
        - packer
        - vmwareworkstation
        - virtualbox
        - vagrant
        - vagrant-vmware-utility
        - wsl-ubuntu-1804

  - name: Install Vagrant VMware plugin
    command: vagrant plugin install vagrant-vmware-desktop

  # https://www.vagrantup.com/docs/vmware/installation.html
  - name: Copy Vagrant VMware plugin licence file
    copy:
      src: "{{ vagrant_vmware_plugin_licence_file }}"
      dest: "c:/vagrant-vmware-plugin.lic"

  - name: Install Vagrant VMware plugin license
    command: vagrant plugin license vagrant-vmware-desktop c:/vagrant-vmware-plugin.lic

  - name: Remove copy of Vagrant VMware plugin license file
    file:
      path: c:/vagrant-vmware-plugin.lic
      state: absent

  # https://kb.vmware.com/s/article/1009244
  # https://communities.vmware.com/message/2104737#2104737
  - name: Activate VMware licence
    command: vmware-vmx --new-sn "{{ vmware_licence_key }}"

  - name: Copy wsl-vagrant wrapper
    win_copy:
      src: files/wsl-vagrant
      dest: "c:\\ProgramData\\chocolatey\\bin\\wsl-vagrant"
    become: true

  - name: Install WSL
    win_shell: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux"
    become: true

  - name: Set up WSL
    script: files/wsl-setup.ps1

  - name: Install Ansible in WSL Python
    win_shell: wsl -e pip install ansible

  - name: Download Stage 1 provisioning repositories
    include_tasks:
      file: download_roles.yml
