---
  - name: Enable Windows Subsystem for Linux
    win_shell: Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName Microsoft-Windows-Subsystem-Linux
    become: yes
    register: wsl_enabled

  - name: Reboot if necessary for WSL functionality
    win_reboot:
    when: "{{ 'RestartNeeded : True' in wsl_enabled.stdout }}"

  - name: Install Ubuntu 18.04 for WSL
    win_chocolatey:
      name: wsl-ubuntu-1804
    become: yes

  - name: Copy wsl-vagrant wrapper
    win_copy:
      src: files/wsl-vagrant
      dest: "c:\\ProgramData\\chocolatey\\bin\\wsl-vagrant"
    become: true

  - name: Update WSL apt database
    win_shell: wsl -e apt update

  - name: Install pip in WSL Python 3
    win_shell: wsl -e apt install -y python3-pip

  - name: Install Ansible in WSL Python
    win_shell: wsl -e pip3 install ansible pywinrm

  - name: Set up WSL automount
    win_shell: wsl -u root echo -e [automount]\\nenabled = true\\nroot = /mnt/\\noptions = '\"metadata,umask=22,fmask=11\"'\\n `>> /etc/wsl.conf

  - name: Check WSL default user
    win_shell: wsl -e whoami
    register: wsl_user

  - name: Create WSL user {{ local_user }}
    win_shell: wsl -e useradd {{ local_user }}
    when: "{{ 'root' in wsl_user.stdout_lines }}"

  - name: Change password for {{ local_user }} in WSL
    win_shell: wsl -e chpasswd {{ local_user }}:{{ wsl_user_password }}
    when: "{{ 'root' in wsl_user.stdout_lines }}"

  # TODO: add {{ local_user }} to sudoers and switch default uid to 1000 via registry
  #- name: Add {{ local_user }} to WSL sudoers
  #  win_shell: wsl -e usermod {{ local_user }} -G wheel
  #  when: "{{ 'root' in wsl_user.stdout_lines }}"

  - name: Switch default WSL user to {{ local_user }}
    win_regedit:
      path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss\{d5f3cdf5-e49e-4d34-8107-9beec78b9a41}
      name: DefaultUid
      data: 1000

  - name: Copy SSH keys to WSL user {{ local_user }}
    win_shell: wsl -u {{ local_user }} -e mkdir -p ~/.ssh; cp "/mnt/c/Users/{{ local_user }}/.ssh/id_rsa*" ~/.ssh/

  - name: Set SSH key permissions for WSL user {{ local_user }}
    win_shell: wsl -u {{ local_user }} -e chmod 644 ~/.ssh/id_rsa.pub; chmod 600 ~/.ssh/id_rsa
